"""
morph_app.py — GeoSemantics-Morph Flask server (port 5001).

Start with:
    python morph_app.py

Requires _poi_cache/morph_data.json (run precompute_morph.py first).
Optionally loads inference.py for live GNN queries (Lens mode → Click).
"""
import os, json, math
import numpy as np
from flask import Flask, jsonify, request, send_from_directory

DATA_PATH          = os.path.join('_poi_cache', 'morph_data.json')
ALL_PLACES_PATH    = os.path.join('_poi_cache', 'all_places_umap.json')
SCALE_LABELS  = ['Micro (200 m)', 'Meso (700 m)', 'Macro (2 km)']
SCALE_SHORT   = ['Micro', 'Meso', 'Macro']
SCALE_DESCS   = [
    "street-level character — defined by what's immediately within 200 m.",
    "neighbourhood context shapes identity — the surrounding quarter matters most.",
    "city/landscape scale defines identity — district structure overrides street details.",
]

app = Flask(__name__, static_folder='static')

# Load precomputed data once at startup
_data: dict = {'locations': [], 'n_locations': 0}

def _load():
    global _data
    if not os.path.exists(DATA_PATH):
        print(f'[morph] {DATA_PATH} not found — run: python precompute_morph.py')
        return
    with open(DATA_PATH, 'r', encoding='utf-8') as fh:
        _data = json.load(fh)
    print(f'[morph] Loaded {len(_data["locations"])} locations from {DATA_PATH}')

_load()

# ── All-places UMAP data (generated by precompute_all_places.py) ──────────────
_all_places: dict = {'places': [], 'n_places': 0}

def _load_all_places():
    global _all_places
    if not os.path.exists(ALL_PLACES_PATH):
        print(f'[all_places] {ALL_PLACES_PATH} not found — run: python precompute_all_places.py --fast')
        return
    with open(ALL_PLACES_PATH, 'r', encoding='utf-8') as fh:
        _all_places = json.load(fh)
    print(f'[all_places] Loaded {_all_places["n_places"]} places from {ALL_PLACES_PATH}')

_load_all_places()

_places = []

def _load_places():
    global _places
    df_path = os.path.join('_poi_cache', 'df.parquet')
    if not os.path.exists(df_path):
        print('[places] df.parquet not found — search will fall back to precomputed only')
        return
    try:
        import pandas as pd
        df_all = pd.read_parquet(df_path)
        wanted_types = {'city', 'town', 'village', 'suburb', 'neighbourhood'}
        df_filtered = df_all[df_all['place'].isin(wanted_types) & df_all['name'].notna() & (df_all['name'] != '')]
        places_list = []
        seen = set()
        for _, row in df_filtered.iterrows():
            name = str(row['name']).strip()
            lat = float(row['lat'])
            lon = float(row['lon'])
            place = str(row['place'])
            key = (name.lower(), round(lat, 3), round(lon, 3))
            if key not in seen:
                seen.add(key)
                places_list.append({
                    'name': name,
                    'lat': lat,
                    'lon': lon,
                    'place': place
                })
        _places = places_list
        print(f'[places] Loaded {len(_places)} Austrian places from df.parquet')
    except Exception as e:
        print(f'[places] Error loading places: {e}')

_load_places()

# Optionally load inference for live queries
_inf = None
try:
    import inference as _inf
    print('[morph] inference module available — live GNN queries enabled')
except Exception as e:
    print(f'[morph] inference not loaded ({e}) — live queries disabled')

# Helpers
def _cosine(a, b):
    a, b = np.asarray(a, dtype=float), np.asarray(b, dtype=float)
    na, nb = np.linalg.norm(a), np.linalg.norm(b)
    return float(np.dot(a, b) / (na * nb)) if na > 0 and nb > 0 else 0.0

def _haversine(lat1, lon1, lat2, lon2):
    R = 6_371_000
    p, q   = math.radians(lat1), math.radians(lat2)
    dp, dl = math.radians(lat2 - lat1), math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p) * math.cos(q) * math.sin(dl / 2) ** 2
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

def _nearest_geo(lat, lon):
    best_id, best_d = -1, float('inf')
    for loc in _data['locations']:
        d = _haversine(lat, lon, loc['lat'], loc['lon'])
        if d < best_d:
            best_d, best_id = d, loc['id']
    return best_id, best_d

def _nearest_emb(embedding):
    best_id, best_sim = -1, -2.0
    for loc in _data['locations']:
        if not loc.get('embedding'):
            continue
        if len(embedding) != len(loc['embedding']):
            continue
        s = _cosine(embedding, loc['embedding'])
        if s > best_sim:
            best_sim, best_id = s, loc['id']
    return best_id

def _loc_by_id(loc_id):
    return next((l for l in _data['locations'] if l['id'] == loc_id), None)

def _lerp_dims(a, b, t):
    keys = set(a) | set(b)
    raw  = {k: (1 - t) * a.get(k, 0) + t * b.get(k, 0) for k in keys}
    total = sum(raw.values()) + 1e-9
    return {k: round(v / total, 4) for k, v in raw.items()}

def _lerp_list(a, b, t):
    return [round((1 - t) * x + t * y, 4) for x, y in zip(a, b)]

def _lerp_arch(a, b, t):
    keys = set(a) | set(b)
    return {k: round((1 - t) * a.get(k, 0) + t * b.get(k, 0), 4) for k in keys}


# Flowing-prose opener for each character label, keyed to the exact strings
# inference._location_label can return — covers every label in current use.
_LABEL_PHRASE = {
    'Historic / Tourist':         'a historic district with a strong tourist character',
    'Tourist Destination':        'a tourist destination',
    'Heritage Site':              'a heritage site',
    'Nature Tourism':             'a nature-tourism area, where outdoor attractions meet visitor infrastructure',
    'Natural / Alpine Area':      'a remote alpine area',
    'Urban Transport Hub':        'an urban transport hub',
    'Urban Center':               'an urban center',
    'Industrial / Infrastructure':'an industrial / infrastructure zone',
    'Natural Fringe':             'the natural fringe of a settlement',
    'Village / Community':        'a small village community',
    'Mixed Urban':                'a mixed-use urban area',
    'Peri-Urban':                 'a peri-urban area, transitional between city and countryside',
    'Remote Area':                'a remote, sparsely-mapped area',
}


def _dim_summary_phrase(dims):
    """'predominantly Nature (81%) with a secondary Transport presence (12%)'"""
    ranked = sorted(dims.items(), key=lambda kv: kv[1], reverse=True)
    ranked = [(k, v) for k, v in ranked if v > 0.01]
    if not ranked:
        return 'no clear dominant character'
    top_k, top_v = ranked[0]
    phrase = f'predominantly <b>{top_k}</b> ({round(top_v*100)}%)'
    if len(ranked) > 1 and ranked[1][1] >= 0.10:
        k2, v2 = ranked[1]
        phrase += f' with a secondary <b>{k2}</b> presence ({round(v2*100)}%)'
    return phrase


def _influential_features_phrase(top_pois, max_items=4):
    """'Großglockner, Pasterze Glacier, and 8 hiking paths' — prefers genuinely
    named landmarks (where OSM gave a real name, not just a category fallback)
    over generic category mentions, and groups remaining same-category POIs
    with a count instead of repeating the category name."""
    if not top_pois:
        return None, []
    named, named_lc, cat_counts, cat_order = [], [], {}, []
    for p in top_pois[:20]:               # only the most saliency-influential POIs
        name, value, cat = p.get('name', ''), p.get('value', ''), p.get('category', '')
        name = name.strip()
        # A "real" name must differ from the generic category fallback AND
        # look like an actual name — OSM occasionally has junk values like
        # "-2" or a bare house number in the name field.
        is_real_name = (bool(name) and name.lower() != str(value).strip().lower()
                         and len(name) >= 2 and any(ch.isalpha() for ch in name))
        if is_real_name:
            nlc = name.strip().lower()
            # Skip near-duplicates: same name in another case, or one name
            # contained inside another (e.g. "Hallstatt" vs "Enchanting Hallstatt")
            if any(nlc == e or nlc in e or e in nlc for e in named_lc):
                continue
            named.append(name)
            named_lc.append(nlc)
        else:
            label = value or cat or 'feature'
            # Same plausibility check — category fallback values can also be
            # OSM junk (e.g. a bare "-2" from a level/entrance tag).
            if not (len(label.strip()) >= 2 and any(ch.isalpha() for ch in label)):
                label = cat if (cat and any(ch.isalpha() for ch in cat)) else 'feature'
            if label not in cat_counts:
                cat_order.append(label)
            cat_counts[label] = cat_counts.get(label, 0) + 1

    parts = list(named)
    for label in cat_order:
        n = cat_counts[label]
        parts.append(f'{n} {label}{"s" if n > 1 else ""}' if n > 1 else label)
        if len(parts) >= max_items:
            break
    parts = parts[:max_items]

    if not parts:
        return None, []
    if len(parts) == 1:
        joined = parts[0]
    elif len(parts) == 2:
        joined = f'{parts[0]} and {parts[1]}'
    else:
        joined = ', '.join(parts[:-1]) + f', and {parts[-1]}'
    return joined, named


def _nl_lens(loc):
    dims  = loc.get('semantic_dims', {})
    td    = max(dims, key=dims.get) if dims else '–'
    sa    = loc.get('scale_attention', [1/3]*3)
    si    = int(np.argmax(sa))
    sp    = round(sa[si] * 100)
    descs = [
        "street-level character dominates — defined by what's immediately around you",
        'neighbourhood context shapes this place — the surrounding quarter matters most',
        'city-level structure defines identity — district type matters more than individual streets',
    ]
    arch  = loc.get('archetype_similarities', {})
    ba    = max(arch, key=arch.get) if arch else '–'
    bap   = round((arch.get(ba, 0) + 1) / 2 * 100) if arch else 0
    n     = loc.get('n_pois', 0)
    c     = loc.get('confidence', 0)
    label = loc.get('label', '–')

    if label == '–' or not label or label.strip() == '':
        closest_pin = loc.get('closest_pin_name', '–')
        if ' · ' in closest_pin:
            closest_pin = closest_pin.split(' · ')[0]
        if closest_pin and closest_pin != '–':
            archetype_phrase = f'an area near {closest_pin}'
        else:
            archetype_phrase = 'an unlabelled area'
    else:
        archetype_phrase = _LABEL_PHRASE.get(label, f'an area labelled "{label}"')
    dim_phrase = _dim_summary_phrase(dims)
    why_phrase, named = _influential_features_phrase(loc.get('top_pois', []))

    why_sentence = ''
    if why_phrase:
        verb = 'anchored by' if named else 'shaped primarily by'
        why_sentence = f'This reading is {verb} {why_phrase}. '

    confidence_caveat = ''
    if c < 0.4:
        confidence_caveat = ' — sparse OSM data here, so treat this reading cautiously'

    return (f'<b>{loc["name"]}</b> reads as <b>{archetype_phrase}</b> — {dim_phrase}. '
            f'{why_sentence}'
            f'Identity is set at the <b>{SCALE_LABELS[si]}</b> scale ({sp}%): {descs[si]}. '
            f'Closest comparable archetype: <b>{ba}</b> ({bap}% similarity). '
            f'Based on {n} mapped features here · {c:.0%} confidence{confidence_caveat}.')

def _nl_diff(la, lb, sim_pct, deltas):
    da, db = la.get('semantic_dims', {}), lb.get('semantic_dims', {})
    ta = max(da, key=da.get) if da else '–'
    tb = max(db, key=db.get) if db else '–'
    desc = ('very similar' if sim_pct > 70 else 'moderately similar'
            if sim_pct > 50 else 'distinct' if sim_pct > 35 else 'contrasting')
    sa, sb = la.get('scale_attention', []), lb.get('scale_attention', [])
    sn = ['Micro', 'Meso', 'Macro']
    doma = sn[int(np.argmax(sa))] if sa else '–'
    domb = sn[int(np.argmax(sb))] if sb else '–'
    top = sorted(deltas.items(), key=lambda x: abs(x[1]), reverse=True)
    note = ''
    if top:
        k, v = top[0]
        note = (f'The sharpest contrast is <b>{k}</b>: '
                f'{"A" if v < 0 else "B"} scores {abs(round(v*100))}pp higher. ')
    return (f'<b>{la["name"]}</b> ↔ <b>{lb["name"]}</b> are <b>{desc}</b> ({sim_pct}%). '
            f'{note}'
            f'A is <b>{ta.lower()}</b>-dominant and <b>{doma}</b>-scale; '
            f'B is <b>{tb.lower()}</b>-dominant and <b>{domb}</b>-scale.')

def _nl_morph(la, lb, dims_t, sa_t, arch_t, t):
    td  = max(dims_t, key=dims_t.get) if dims_t else '–'
    tp  = round(dims_t.get(td, 0) * 100)
    si  = int(np.argmax(sa_t))
    sp  = round(sa_t[si] * 100)
    ba  = max(arch_t, key=arch_t.get) if arch_t else '–'
    pct = round(t * 100)
    da, db = la.get('semantic_dims', {}), lb.get('semantic_dims', {})
    ta = max(da, key=da.get) if da else '–'
    tb = max(db, key=db.get) if db else '–'
    if pct < 20:
        trans = f'strongly resembles <b>{la["name"]}</b> — mostly {ta.lower()}'
    elif pct > 80:
        trans = f'strongly resembles <b>{lb["name"]}</b> — mostly {tb.lower()}'
    else:
        trans = (f'blending <b>{ta.lower()}</b> → <b>{tb.lower()}</b> '
                 f'(currently {td.lower()} at {tp}%)')
    return (f'At <b>{pct}%</b> from <b>{la["name"]}</b> to <b>{lb["name"]}</b>, '
            f'identity {trans}. '
            f'Scale anchor: <b>{SCALE_LABELS[si]}</b> ({sp}%). '
            f'Closest archetype: <b>{ba}</b>.')

def _build_transition_explanation(la, lb, dims_a, dims_b):
    """
    Build a detailed transition explanation answering:
    - What changes first / most?
    - Which dimension changes most?
    - Which scale drives the change?
    - Which node types appear / disappear?
    """
    da = la.get('semantic_dims', dims_a)
    db = lb.get('semantic_dims', dims_b)
    all_dims = set(da) | set(db)

    # Dimension deltas (B - A)
    deltas = {k: round(db.get(k, 0) - da.get(k, 0), 3) for k in all_dims}
    sorted_deltas = sorted(deltas.items(), key=lambda x: abs(x[1]), reverse=True)

    # What changes most?
    top_k, top_v = sorted_deltas[0] if sorted_deltas else ('–', 0)
    direction    = 'increases' if top_v > 0 else 'decreases'

    # Which dims appear / disappear above threshold
    threshold = 0.08
    appears   = [k for k, v in deltas.items() if v  >  threshold]
    fades     = [k for k, v in deltas.items() if v  < -threshold]
    stable    = [k for k in all_dims
                 if da.get(k, 0) >= threshold and db.get(k, 0) >= threshold
                 and abs(deltas.get(k, 0)) < threshold]

    # Scale attention shift
    sa_a  = la.get('scale_attention', [1/3]*3)
    sa_b  = lb.get('scale_attention', [1/3]*3)
    dom_a = int(np.argmax(sa_a))
    dom_b = int(np.argmax(sa_b))
    scale_shift = ''
    if dom_a != dom_b:
        scale_shift = (f'Scale anchor shifts from <b>{SCALE_SHORT[dom_a]}</b> '
                       f'to <b>{SCALE_SHORT[dom_b]}</b> along the path. ')
    else:
        scale_shift = f'Scale remains <b>{SCALE_SHORT[dom_a]}</b>-dominant throughout. '

    # Build NL
    nl_parts = []
    if top_k != '–':
        nl_parts.append(
            f'<b>{top_k}</b> {direction} most sharply '
            f'({abs(round(top_v*100))} pp).')
    if appears:
        nl_parts.append(f'Emerging at B: <b>{", ".join(appears)}</b>.')
    if fades:
        nl_parts.append(f'Fading toward B: <b>{", ".join(fades)}</b>.')
    if stable:
        nl_parts.append(f'Stable throughout: {", ".join(stable)}.')
    nl_parts.append(scale_shift)

    return {
        'top_changing_dim':   top_k,
        'top_delta_pp':       round(top_v * 100, 1),
        'appears_at_b':       appears,
        'fades_toward_b':     fades,
        'stable_dims':        stable,
        'scale_shift':        scale_shift,
        'nl':                 ' '.join(nl_parts),
        'dim_deltas':         sorted_deltas[:7],
    }

# Routes
@app.route('/favicon.ico')
def favicon():
    return '', 204

@app.route('/')
def index():
    resp = send_from_directory('static', 'morph.html')
    resp.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    resp.headers['Pragma'] = 'no-cache'
    return resp

@app.route('/api/morph/data')
def morph_data_route():
    # Strip embeddings before sending to save bandwidth (~50% size reduction)
    slim = []
    for loc in _data['locations']:
        d = {k: v for k, v in loc.items() if k != 'embedding'}
        slim.append(d)
    return jsonify({'locations': slim, 'n_locations': len(slim)})

@app.route('/api/morph/data_full')
def morph_data_full():
    """Full data including embeddings — used for client-side cosine search."""
    return jsonify(_data)

@app.route('/api/morph/all_places_umap')
def all_places_umap():
    """
    Slim endpoint: {name, lat, lon, ux, uy, dominant_dim, place_type, is_seed}
    for ALL Austrian places (generated by precompute_all_places.py).

    Optional query params:
      bbox=lat_min,lon_min,lat_max,lon_max  — server-side spatial filter
    """
    places = _all_places.get('places', [])

    bbox_str = request.args.get('bbox')
    if bbox_str:
        try:
            lat_min, lon_min, lat_max, lon_max = map(float, bbox_str.split(','))
            places = [
                p for p in places
                if lat_min <= p['lat'] <= lat_max and lon_min <= p['lon'] <= lon_max
            ]
        except Exception:
            pass  # ignore malformed bbox

    # Slim fields only — no semantic_dims (saves bandwidth for large sets)
    slim = [{
        'name':         p['name'],
        'lat':          p['lat'],
        'lon':          p['lon'],
        'ux':           p.get('ux', 0.5),
        'uy':           p.get('uy', 0.5),
        'dominant_dim': p.get('dominant_dim', 'Community'),
        'place_type':   p.get('place_type', 'village'),
        'is_seed':      p.get('is_seed', False),
    } for p in places]

    return jsonify({
        'places':   slim,
        'n_places': len(slim),
        'total':    _all_places.get('n_places', 0),
        'method':   _all_places.get('method', 'unknown'),
    })

SEMANTIC_GRID_PATH = os.path.join('_poi_cache', 'semantic_grid.json')

@app.route('/api/morph/semantic_grid')
def semantic_grid():
    """
    Dense Austria-wide character grid for the 'Character Layer' map overlay
    (generated by precompute_semantic_grid.py). Read fresh from disk on every
    request — the precompute script checkpoints every 200 cells, so toggling
    the layer on always reflects whatever progress has been made so far,
    with no server restart needed while that job is still running.

    Optional query params:
      bbox=lat_min,lon_min,lat_max,lon_max  — server-side spatial filter
    """
    if not os.path.exists(SEMANTIC_GRID_PATH):
        return jsonify({'cells': [], 'n_cells': 0, 'has_data': False,
                         'note': 'Run: python precompute_semantic_grid.py'})
    try:
        with open(SEMANTIC_GRID_PATH, 'r', encoding='utf-8') as fh:
            data = json.load(fh)
    except Exception as e:
        return jsonify({'cells': [], 'n_cells': 0, 'has_data': False, 'error': str(e)})

    cells = data.get('cells', [])
    bbox_str = request.args.get('bbox')
    if bbox_str:
        try:
            lat_min, lon_min, lat_max, lon_max = map(float, bbox_str.split(','))
            cells = [c for c in cells
                     if lat_min <= c['lat'] <= lat_max and lon_min <= c['lon'] <= lon_max]
        except Exception:
            pass  # ignore malformed bbox

    return jsonify({
        'cells':    cells,
        'n_cells':  len(cells),
        'grid':     data.get('grid'),
        'radius':   data.get('radius'),
        # Matches precompute_semantic_grid.py's LAT_RANGE/LON_RANGE — sent
        # along so the frontend can size each cell to the grid spacing
        # without duplicating those constants independently.
        'lat_range': [46.30, 49.05],
        'lon_range': [9.40, 17.20],
        'has_data': len(cells) > 0,
    })

SEMANTIC_GRID_IMAGE_PATH = os.path.join('_poi_cache', 'semantic_grid.png')

@app.route('/api/morph/semantic_grid_image')
def semantic_grid_image():
    """
    Smoothly-interpolated raster version of the character grid (generated
    by render_character_layer.py from the same semantic_grid.json cells) —
    served as a single image overlay instead of thousands of individual
    rectangles, which removes the hard cell-to-cell seams and fills gaps
    via distance-weighted interpolation from real neighbouring cells
    instead of leaving them blank.
    """
    if not os.path.exists(SEMANTIC_GRID_IMAGE_PATH):
        return jsonify({'error': 'Run: python render_character_layer.py'}), 404
    resp = send_from_directory('_poi_cache', 'semantic_grid.png')
    resp.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    return resp

@app.route('/api/morph/semantic_grid_image_region')
def semantic_grid_image_region():
    """
    Same interpolated render as semantic_grid_image, but cropped to the
    CURRENT map viewport and sized to its actual pixel dimensions instead
    of the fixed whole-Austria overview image. Leaflet would otherwise just
    stretch that one low-res country-wide image as you zoom in, which looks
    increasingly blurry without showing anything more specific. Re-rendering
    at the viewport's own resolution is fast (well under a second — this is
    a numpy/PIL interpolation over ~3,700 points, not a model forward pass)
    and reveals the existing grid data more crisply. It does not add ground
    truth finer than the original precompute's ~700m sampling radius /
    ~3km grid spacing — a tiny viewport may still only have one or two real
    cells nearby, just rendered sharply instead of blown up from afar.

    Required query params:
      bounds=lat_min,lon_min,lat_max,lon_max
      w, h — target pixel size (each capped at 1200 to bound compute/payload)
    """
    if not os.path.exists(SEMANTIC_GRID_PATH):
        return jsonify({'error': 'Run: python precompute_semantic_grid.py'}), 404
    try:
        with open(SEMANTIC_GRID_PATH, 'r', encoding='utf-8') as fh:
            data = json.load(fh)
        cells = data.get('cells', [])
        if not cells:
            return jsonify({'error': 'No cells in semantic_grid.json yet'}), 404

        lat_min, lon_min, lat_max, lon_max = map(float, request.args['bounds'].split(','))
        w = min(1200, max(50, int(request.args.get('w', 600))))
        h = min(1200, max(50, int(request.args.get('h', 600))))

        import io
        import _old.render_character_layer as rcl
        img = rcl.render_image(cells, (lat_min, lat_max), (lon_min, lon_max), width=w, height=h)
        buf = io.BytesIO()
        img.save(buf, format='PNG')
        buf.seek(0)
        resp = app.response_class(buf.getvalue(), mimetype='image/png')
        resp.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
        return resp
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({'error': str(e)}), 500

@app.route('/api/morph/nearest', methods=['POST'])
def morph_nearest():
    body = request.get_json(force=True)
    lat, lon = float(body['lat']), float(body['lon'])
    loc_id, dist_m = _nearest_geo(lat, lon)
    if loc_id < 0:
        return jsonify({'error': 'No precomputed locations loaded.'})
    loc = _loc_by_id(loc_id)
    return jsonify({'location': loc, 'dist_m': round(dist_m), 'nl': _nl_lens(loc)})

@app.route('/api/morph/diff', methods=['POST'])
def morph_diff():
    body = request.get_json(force=True)
    ids = body.get('ids', [])
    
    # Fallback to old format if 'ids' isn't explicitly passed
    if not ids and 'id_a' in body and 'id_b' in body:
        ids = [int(body['id_a']), int(body['id_b'])]
        
    locs = []
    for loc_id in ids:
        l = _loc_by_id(int(loc_id))
        if l:
            locs.append(l)
            
    if len(locs) < 2:
        return jsonify({'error': 'Need at least 2 valid locations.'})

    # Return distances between all pairs
    pairwise = []
    for i in range(len(locs)):
        for j in range(i + 1, len(locs)):
            a, b = locs[i], locs[j]
            sim = None
            if a.get('embedding') and b.get('embedding'):
                sim = round(_cosine(a['embedding'], b['embedding']), 4)
            sim_pct = round((sim + 1) / 2 * 100) if sim is not None else 0
            
            da, db = a.get('semantic_dims', {}), b.get('semantic_dims', {})
            all_keys = set(da) | set(db)
            deltas = {k: round(db.get(k, 0) - da.get(k, 0), 4) for k in all_keys}
            
            pairwise.append({
                'loc1_idx': i,
                'loc2_idx': j,
                'loc1_id': a['id'],
                'loc2_id': b['id'],
                'embedding_sim': sim,
                'similarity_pct': sim_pct,
                'semantic_deltas': deltas
            })

    return jsonify({
        'locations': locs,
        'pairwise': pairwise
    })

@app.route('/api/morph/interpolate', methods=['POST'])
def morph_interpolate():
    body = request.get_json(force=True)
    t    = max(0.0, min(1.0, float(body.get('t', 0.5))))
    la   = _loc_by_id(int(body['id_a']))
    lb   = _loc_by_id(int(body['id_b']))
    if not la or not lb:
        return jsonify({'error': 'Location ID not found.'})

    dims_t  = _lerp_dims(la.get('semantic_dims', {}),    lb.get('semantic_dims', {}),    t)
    scale_t = _lerp_list(la.get('scale_attention', [1/3]*3), lb.get('scale_attention', [1/3]*3), t)
    arch_t  = _lerp_arch(la.get('archetype_similarities', {}), lb.get('archetype_similarities', {}), t)

    # Interpolate embedding → nearest precomputed for POI display
    nearest_id = la['id']
    if la.get('embedding') and lb.get('embedding'):
        emb_t = np.array([(1-t)*a + t*b for a, b in zip(la['embedding'], lb['embedding'])])
        n     = np.linalg.norm(emb_t)
        if n > 1e-9:
            emb_t /= n
        nearest_id = _nearest_emb(emb_t.tolist())

    nearest = _loc_by_id(nearest_id) or la

    return jsonify({
        'semantic_dims':          dims_t,
        'scale_attention':        scale_t,
        'archetype_similarities': arch_t,
        'lat':  round((1-t)*la['lat'] + t*lb['lat'], 5),
        'lon':  round((1-t)*la['lon'] + t*lb['lon'], 5),
        'ux':   round((1-t)*la.get('ux', 0.5) + t*lb.get('ux', 0.5), 4),
        'uy':   round((1-t)*la.get('uy', 0.5) + t*lb.get('uy', 0.5), 4),
        'dominant_dim':    max(dims_t, key=dims_t.get) if dims_t else '–',
        'dominant_arch':   max(arch_t, key=arch_t.get) if arch_t else '–',
        'nearest_pois_id': nearest_id,
        'top_pois':        nearest.get('top_pois', []),
        'nl':              _nl_morph(la, lb, dims_t, scale_t, arch_t, t),
        't':               t,
    })

def _build_live_loc(lat, lon, radius=600, model='auto'):
    """Run GNN query and build a full location dict.

    model: 'v2' | 'v3' | 'auto'
      'auto' = prefer V3 character + V2 embedding (original behaviour)
      'v2'   = force V2 character + V2 embedding
      'v3'   = force V3 character + V3 embedding
    Returns None on failure.
    """
    if _inf is None:
        return None
    sal, sel_df, _ = _inf.get_saliency(lat, lon, radius)
    if sal is None or len(sal) == 0:
        return None

    # Character selection
    want_v3_char = model in ('v3', 'auto')
    want_v2_char = model in ('v2', 'auto', 'v1')
    char = None
    if want_v3_char and hasattr(_inf, 'get_location_character_v3') and _inf._v3_node_types is not None:
        char = _inf.get_location_character_v3(lat, lon, radius)
    if char is None and want_v2_char:
        char = _inf.get_location_character(lat, lon, radius)
    if char is None:
        return None

    # Confidence score
    conf_result = None
    if hasattr(_inf, 'get_confidence_score'):
        conf_result = _inf.get_confidence_score(lat, lon, radius)
    confidence = conf_result['score'] if conf_result else (
        round(min(1.0, len(sal)/200)*0.45 + float(np.clip(sal.mean(), 0, None))*0.55, 3))

    # Multi-scale character
    multiscale = None
    if hasattr(_inf, 'get_multiscale_character'):
        try:
            multiscale = _inf.get_multiscale_character(lat, lon)
        except Exception:
            multiscale = None

    s_min   = sal.min(); s_range = (sal.max() - s_min) + 1e-8
    sal_n   = (sal - s_min) / s_range
    pois    = []
    for i, (_, row) in enumerate(sel_df.iterrows()):
        cat, val = _inf.get_poi_label(row)
        pois.append({'name': str(row.get('name', '') or val), 'category': cat,
                     'value': val, 'saliency': round(float(sal_n[i]), 4),
                     'lat': float(row['lat']), 'lon': float(row['lon'])})
    pois.sort(key=lambda p: p['saliency'], reverse=True)

    # Embedding selection
    emb, scale_attn, char_src = None, [1/3]*3, char.get('source', 'v2')
    prefer_v3_emb = (model == 'v3')
    
    if model == 'v1':
        emb_v1, _ = _inf.get_embedding(lat, lon, radius)
        if emb_v1 is not None:
            emb = emb_v1.tolist()
            char_src = 'v1'
    elif not prefer_v3_emb and _inf.v2_available:
        emb_v2, attn = _inf.get_embedding_v2(lat, lon)
        if emb_v2 is not None:
            emb        = emb_v2.tolist()
            scale_attn = attn.tolist() if attn is not None else scale_attn
            char_src   = 'v2'
    if emb is None and _inf.v3_available:
        emb_v3, attn = _inf.get_embedding_v3(lat, lon)
        if emb_v3 is not None:
            emb        = emb_v3.tolist()
            scale_attn = attn.tolist() if attn is not None else scale_attn
    # v3 explicit: try v3 first, then v2 fallback
    if prefer_v3_emb and emb is None and _inf.v2_available:
        emb_v2, attn = _inf.get_embedding_v2(lat, lon)
        if emb_v2 is not None:
            emb        = emb_v2.tolist()
            scale_attn = attn.tolist() if attn is not None else scale_attn

    nearest_id = _nearest_emb(emb) if emb else -1
    if nearest_id < 0:
        nearest_id, _ = _nearest_geo(lat, lon)
    nearest = _loc_by_id(nearest_id)

    return {
        'name':                   f'{lat:.4f}, {lon:.4f}',
        'lat': lat, 'lon': lon,
        'label':                  char.get('label', '–'),
        'embedding':              emb,
        'ux':                     nearest.get('ux', 0.5) if nearest else 0.5,
        'uy':                     nearest.get('uy', 0.5) if nearest else 0.5,
        'semantic_dims':          char.get('char_dims', {}),
        'scale_attention':        [round(x, 4) for x in scale_attn],
        'archetype_similarities': nearest.get('archetype_similarities', {}) if nearest else {},
        'top_pois':               pois,
        'closest_pin_name':       nearest.get('name', '–') if nearest else '–',
        'n_pois':                 char.get('n_pois', len(sal)),
        'avg_saliency':           round(float(sal_n.mean()), 4),
        'confidence':             confidence,
        'confidence_detail':      conf_result,
        'multiscale':             multiscale,
        'char_source':            char.get('source', 'v2'),
    }

@app.route('/api/morph/analyze', methods=['POST'])
def morph_analyze():
    """Analyze any lat/lon — live GNN if available, nearest precomputed otherwise."""
    try:
        body   = request.get_json(force=True)
        lat    = float(body['lat'])
        lon    = float(body['lon'])
        radius = int(body.get('radius', 600))
        model  = body.get('model', 'auto')
        if model not in ('v1', 'v2', 'v3', 'auto'):
            model = 'auto'
        loc = _build_live_loc(lat, lon, radius, model=model)
        if loc is not None:
            return jsonify({'location': loc, 'nl': _nl_lens(loc), 'source': 'live'})
        # Fallback: nearest precomputed
        loc_id, dist_m = _nearest_geo(lat, lon)
        if loc_id < 0:
            return jsonify({'error': 'No locations available.'})
        loc = _loc_by_id(loc_id)
        return jsonify({'location': loc, 'dist_m': round(dist_m),
                        'nl': _nl_lens(loc), 'source': 'precomputed'})
    except Exception as e:
        import traceback
        tb = traceback.format_exc()
        print(tb, flush=True)
        return jsonify({'error': f'Live inference fail: {str(e)}', 'traceback': tb}), 500

@app.route('/api/morph/live_query', methods=['POST'])
def morph_live_query():
    """Run a real GNN query at lat/lon (requires inference module)."""
    if _inf is None:
        return jsonify({'error': 'inference module not loaded on this server.'})
    body   = request.get_json(force=True)
    lat    = float(body['lat'])
    lon    = float(body['lon'])
    radius = int(body.get('radius', 600))
    loc = _build_live_loc(lat, lon, radius)
    if loc is None:
        return jsonify({'error': 'No POIs found nearby.'})
    return jsonify({'location': loc, 'nl': _nl_lens(loc)})

@app.route('/api/morph/transition_explain', methods=['POST'])
def morph_transition_explain():
    """Explain the semantic transition between two locations."""
    body = request.get_json(force=True)
    la   = _loc_by_id(int(body['id_a']))
    lb   = _loc_by_id(int(body['id_b']))
    if not la or not lb:
        return jsonify({'error': 'Location ID not found.'})

    expl = _build_transition_explanation(la, lb, la.get('semantic_dims', {}),
                                          lb.get('semantic_dims', {}))
    return jsonify({'explanation': expl})

@app.route('/api/morph/retrieval', methods=['POST'])
def morph_retrieval():
    """Find locations most similar to the query by character dimension."""
    body       = request.get_json(force=True)
    lat        = float(body['lat'])
    lon        = float(body['lon'])
    top_k      = int(body.get('top_k', 5))
    mode       = body.get('mode', 'character')   # 'character' | 'embedding' | 'dim'
    dim_filter = body.get('dim_filter', None)

    if _inf is None:
        return jsonify({'error': 'inference module not loaded.'})

    try:
        similar = _inf.get_similar_places(lat, lon, top_k=top_k,
                                           mode=mode, dim_filter=dim_filter)
        return jsonify({'similar': similar, 'mode': mode})
    except Exception as e:
        return jsonify({'error': str(e)})

@app.route('/api/morph/multiscale', methods=['POST'])
def morph_multiscale():
    """Return multi-scale character breakdown for a location."""
    body = request.get_json(force=True)
    lat  = float(body['lat'])
    lon  = float(body['lon'])
    if _inf is None:
        return jsonify({'error': 'inference module not loaded.'})
    try:
        ms   = _inf.get_multiscale_character(lat, lon)
        conf = _inf.get_confidence_score(lat, lon, 500)
        return jsonify({'multiscale': ms, 'confidence': conf})
    except Exception as e:
        return jsonify({'error': str(e)})

# Feature 1 — Reverse Semantic Search
_DIM_KEYS = ['Urban', 'Tourism', 'Heritage', 'Nature', 'Transport', 'Infrastructure', 'Community']

def _char_sim_local(d1, d2):
    """Euclidean character similarity with Nature<->Urban contrastive penalty."""
    v1 = [d1.get(k, 0.0) for k in _DIM_KEYS]
    v2 = [d2.get(k, 0.0) for k in _DIM_KEYS]
    dist = sum((a - b) ** 2 for a, b in zip(v1, v2)) ** 0.5 / 1.414
    sim = max(0.0, 1.0 - dist)
    nat1, urb1 = d1.get('Nature', 0), d1.get('Urban', 0)
    nat2, urb2 = d2.get('Nature', 0), d2.get('Urban', 0)
    contrast = (nat1 - urb1) * (urb2 - nat2)
    if contrast > 0.05:
        sim = max(0.0, sim - min(0.40, contrast * 0.65))
    return round(sim, 4)

@app.route('/api/morph/semantic_search', methods=['POST'])
def semantic_search():
    """Find precomputed locations matching a target semantic profile."""
    body   = request.get_json(force=True)
    target = body.get('dims', {})
    top_k  = int(body.get('top_k', 30))

    total = sum(target.values()) or 1
    target = {k: round(v / total, 4) for k, v in target.items() if v > 0}

    results = []
    for loc in _data['locations']:
        dims = loc.get('semantic_dims', {})
        if not dims:
            continue
        sim = _char_sim_local(target, dims)
        results.append({
            'name':          loc.get('name', '?'),
            'lat':           loc['lat'],
            'lon':           loc['lon'],
            'label':         loc.get('label', '-'),
            'id':            loc['id'],
            'similarity':    sim,
            'semantic_dims': dims,
            'confidence':    loc.get('confidence', 0.5),
        })
    results.sort(key=lambda x: x['similarity'], reverse=True)
    # Always return at least 5 closest matches even if similarity is low
    out = results[:max(top_k, 5)]
    return jsonify({'results': out, 'n_total': len(results), 'target': target})

# Feature 2 — Predictive Sandbox
_SANDBOX_CHAR_MAP = {
    'amenity': 'Urban', 'shop': 'Urban', 'building': 'Infrastructure',
    'landuse': 'Urban', 'office': 'Urban', 'tourism': 'Tourism',
    'historic': 'Heritage', 'natural': 'Nature', 'leisure': 'Community',
    'waterway': 'Nature', 'highway': 'Transport', 'railway': 'Transport',
    'public_transport': 'Transport', 'aeroway': 'Transport',
    'man_made': 'Infrastructure', 'power': 'Infrastructure',
    'barrier': 'Infrastructure', 'emergency': 'Infrastructure',
    'healthcare': 'Community', 'place': 'Community', 'sport': 'Community',
}

@app.route('/api/morph/sandbox', methods=['POST'])
def sandbox():
    """Counterfactual what-if simulation: splice synthetic POI additions /
    real-POI removals into the ACTUAL local graph at (lat, lon) and rerun
    the trained saliency GNN + V2 embedding model to get a genuine before
    vs. after character reading — not a hand-tuned heuristic bump.

    additions: [{lat, lon, category}]   category e.g. "amenity=restaurant"
    removals:  [{lat, lon, category}]   category kept for display only
    """
    body      = request.get_json(force=True)
    lat       = float(body['lat'])
    lon       = float(body['lon'])
    radius    = int(body.get('radius', 600))
    additions = body.get('additions', [])
    removals  = body.get('removals', [])

    try:
        import _old.whatif as whatif
        result = whatif.simulate(lat, lon, radius, additions, removals)
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({'error': f'Simulation failed: {e}'}), 500

    if result is None:
        return jsonify({'error': 'Not enough real OSM data at this location to simulate.'})

    base_dims = dict(result['baseline_dims'])
    modified  = dict(result['modified_dims'])
    for k in _DIM_KEYS:
        base_dims.setdefault(k, 0.0)
        modified.setdefault(k, 0.0)
    delta       = {k: round(modified.get(k, 0) - base_dims.get(k, 0), 4) for k in _DIM_KEYS}
    top_shifted = max(delta.items(), key=lambda x: abs(x[1]))[0] if delta else '-'

    return jsonify({
        'baseline_dims':          base_dims,
        'modified_dims':          modified,
        'delta':                  delta,
        'similarity_to_baseline': _char_sim_local(base_dims, modified),
        'top_shifted_dim':        top_shifted,
        'n_pois_base':            result['n_pois_before'],
        'n_pois_after':           result['n_pois_after'],
        'n_additions':            result['n_additions'],
        'n_removals':             result['n_removals'],
        'label_base':             result['label_before'],
        'label_after':            result['label_after'],
        'embedding_shift':        result['embedding_shift'],
    })

# WHATIF_CASE_STUDIES and /api/morph/whatif_case_studies route removed

# Feature — GATv2 Attention Edge Visualisation
@app.route('/api/morph/attention_edges', methods=['POST'])
def attention_edges():
    """
    Return top-N GATv2 attention edges for a location (supports both v2 and v3 models).
    Request: {lat, lon, scale, top_n, model (optional: 'v2' or 'v3')}
    Response: {edges: [...], scale_m, n_nodes, type_names, model}
    """
    body      = request.get_json(force=True)
    lat       = float(body['lat'])
    lon       = float(body['lon'])
    scale_idx = int(body.get('scale', 1))   # 0=200m 1=700m 2=2000m
    top_n     = int(body.get('top_n', 150))
    model_req = body.get('model', None)  # 'v2', 'v3', or None

    try:
        import inference as inf
        import torch

        # Model selection logic
        use_v3 = False
        use_v2 = False
        if model_req == 'v1':
            return jsonify({'edges': [], 'scale_m': 200, 'n_nodes': 0, 'type_names': [], 'model': 'v1'})
        elif model_req == 'v3':
            use_v3 = True
        elif model_req == 'v2':
            use_v2 = True
        else:
            # Auto: prefer v3 if available, else v2
            if getattr(inf, 'v3_available', False):
                use_v3 = True
            elif getattr(inf, 'v2_available', False):
                use_v2 = True

        if use_v3:
            if not getattr(inf, 'v3_available', False):
                return jsonify({'error': 'V3 model not available — train geosemantics_v3.pt first'}), 503
            from geosemantics_v3 import build_multiscale_graphs_v3, SCALES, NODE_TYPE_NAMES
            res    = inf._get_v3_resources()
            graphs = build_multiscale_graphs_v3(lat, lon, external_resources=res)
            if graphs is None:
                return jsonify({'error': 'No graph data at this location'}), 404
            sidx  = max(0, min(scale_idx, len(graphs) - 1))
            g     = graphs[sidx]
            model = inf._v3_model
            with torch.no_grad():
                edges = model.get_attention_edges(g, sidx, top_n=top_n)
            # Normalise weights to [0, 1] for line-thickness mapping in frontend
            if edges:
                w_max = max(e['weight'] for e in edges) or 1.0
                for e in edges:
                    e['weight_norm'] = round(e['weight'] / w_max, 4)
            return jsonify({
                'edges':      edges,
                'scale_m':    SCALES[sidx],
                'n_nodes':    int(g.x.size(0)),
                'type_names': NODE_TYPE_NAMES,
                'model':      'v3',
            })
        elif use_v2:
            if not getattr(inf, 'v2_available', False):
                return jsonify({'error': 'V2 model not available — train geosemantics_v2.pt first'}), 503
            from geosemantics_v2 import build_multiscale_graphs, SCALES
            res    = inf._v2_resources
            graphs = build_multiscale_graphs(lat, lon, external_resources=res)
            if graphs is None:
                return jsonify({'error': 'No graph data at this location'}), 404
            sidx  = max(0, min(scale_idx, len(graphs) - 1))
            g     = graphs[sidx]
            model = inf._v2_model
            with torch.no_grad():
                edges = model.get_attention_edges(g, sidx, top_n=top_n)
            if edges:
                w_max = max(e['weight'] for e in edges) or 1.0
                for e in edges:
                    e['weight_norm'] = round(e['weight'] / w_max, 4)
            # V2 is homogeneous: all nodes are POI type (0)
            type_names = ['POI']
            return jsonify({
                'edges':      edges,
                'scale_m':    SCALES[sidx],
                'n_nodes':    int(g.x.size(0)),
                'type_names': type_names,
                'model':      'v2',
            })
        else:
            return jsonify({'error': 'No supported model available (v2 or v3)'}), 503
    except Exception as exc:
        import traceback; traceback.print_exc()
        return jsonify({'error': str(exc)}), 500

# Feature 3 — Temporal Saliency (Time-Machine)
@app.route('/api/morph/temporal', methods=['POST'])
def temporal():
    """Return temporal character snapshots for a location.

    Uses precomputed historical JSON (precompute_temporal.py) if available;
    otherwise multi-scale proxy: smaller radii represent older core character.
    """
    body = request.get_json(force=True)
    lat  = float(body['lat'])
    lon  = float(body['lon'])

    temporal_years = []
    for year in [2018, 2020, 2022, 2024]:
        path = os.path.join('_poi_cache', f'temporal_{year}.json')
        if not os.path.exists(path):
            continue
        try:
            with open(path) as fh:
                snap = json.load(fh)
            best = None
            best_d = float('inf')
            for entry in snap.get('locations', []):
                d = _haversine(lat, lon, entry['lat'], entry['lon'])
                if d < best_d:
                    best_d, best = d, entry
            if best and best_d < 5000:
                temporal_years.append({
                    'year':   year,
                    'dims':   best.get('semantic_dims', {}),
                    'label':  best.get('label', '-'),
                    'source': 'historical',
                    'n_pois': best.get('n_pois', 0),
                })
        except Exception:
            pass

    if len(temporal_years) >= 2:
        return jsonify({'snapshots': temporal_years, 'source': 'historical', 'has_data': True})

    proxy = [(2018, 120), (2020, 250), (2022, 400), (2024, 600)]
    snapshots = []

    if _inf is not None:
        for year, r in proxy:
            char = None
            if hasattr(_inf, 'get_location_character_v3') and _inf._v3_node_types is not None:
                char = _inf.get_location_character_v3(lat, lon, r)
            if char is None:
                char = _inf.get_location_character(lat, lon, r)
            if char:
                snapshots.append({
                    'year':   year,
                    'dims':   char['char_dims'],
                    'label':  char['label'],
                    'source': 'simulated',
                    'radius': r,
                    'n_pois': char.get('n_pois', 0),
                })
    else:
        loc_id, _ = _nearest_geo(lat, lon)
        loc = _loc_by_id(loc_id)
        if not loc:
            return jsonify({'error': 'No location data.', 'has_data': False})
        dims = loc.get('semantic_dims', {})
        dominant = max(dims, key=dims.get) if dims else None
        for year, factor in [(2018, 0.65), (2020, 0.82), (2022, 0.94), (2024, 1.0)]:
            if factor == 1.0:
                sim_dims = dict(dims)
            else:
                sim_dims = {}
                for k, v in dims.items():
                    sim_dims[k] = min(1.0, v + (1-factor)*(1-v)*0.35) if k == dominant else v * factor
                t = sum(sim_dims.values()) or 1
                sim_dims = {k: round(v / t, 4) for k, v in sim_dims.items()}
            snapshots.append({'year': year, 'dims': sim_dims, 'label': loc.get('label', '-'),
                              'source': 'simulated'})

    if not snapshots:
        return jsonify({'error': 'No data available.', 'has_data': False})

    return jsonify({
        'snapshots': snapshots,
        'source':    'simulated',
        'has_data':  True,
        'note':      ('Scale-proxy mode: 120 m radius = 2018 core identity, 600 m = 2024 full context. '
                      'Run precompute_temporal.py for real OSM historical snapshots.'),
    })

# Feature 3b — Time Machine: full precomputed series with genuine embedding drift
_TEMPORAL_SERIES_PATH = os.path.join('_poi_cache', 'temporal_series.json')
_temporal_series_cache = None
_temporal_series_mtime = 0.0

def _load_temporal_series():
    global _temporal_series_cache, _temporal_series_mtime
    if not os.path.exists(_TEMPORAL_SERIES_PATH):
        return None
    try:
        mt = os.path.getmtime(_TEMPORAL_SERIES_PATH)
        if _temporal_series_cache is not None and mt <= _temporal_series_mtime:
            return _temporal_series_cache
        with open(_TEMPORAL_SERIES_PATH, encoding='utf-8') as fh:
            _temporal_series_cache = json.load(fh)
        _temporal_series_mtime = mt
    except Exception:
        pass
    return _temporal_series_cache

@app.route('/api/morph/places/search')
def search_places():
    q = request.args.get('q', '').strip().lower()
    if not q:
        return jsonify({'results': []})

    prefix_matches = []
    substring_matches = []
    
    precomputed_data = _load_temporal_series() or {}
    seen_coords = set()
    
    # 1. Search precomputed locations
    for k, loc in precomputed_data.items():
        name_lower = loc['name'].lower()
        item = {
            'name': loc['name'],
            'lat': loc['lat'],
            'lon': loc['lon'],
            'place': loc.get('archetype', 'Precomputed'),
            'precomputed': True,
            'id': int(k)
        }
        seen_coords.add((round(loc['lat'], 3), round(loc['lon'], 3)))
        if name_lower.startswith(q):
            prefix_matches.append(item)
        elif q in name_lower:
            substring_matches.append(item)
            
    # 2. Search general places
    if _places:
        for p in _places:
            coord_key = (round(p['lat'], 3), round(p['lon'], 3))
            if coord_key in seen_coords:
                continue
            name_lower = p['name'].lower()
            item = {
                'name': p['name'],
                'lat': p['lat'],
                'lon': p['lon'],
                'place': p['place'].capitalize(),
                'precomputed': False,
                'id': None
            }
            if name_lower.startswith(q):
                prefix_matches.append(item)
            elif q in name_lower:
                substring_matches.append(item)

    results = prefix_matches + substring_matches
    return jsonify({'results': results[:50]})

@app.route('/api/morph/temporal_live', methods=['POST'])
def temporal_live():
    """Live (uncached) historical fetch for an arbitrary map click — same
    real Overpass attic + trained-model pipeline as precompute_temporal.py,
    just for one point. Skips 2010 (frequently empty / low-value) to keep
    wait time bounded; this still issues several real Overpass requests so
    it genuinely takes ~15-30s — the frontend shows an explicit wait state."""
    body = request.get_json(force=True)
    lat = float(body['lat'])
    lon = float(body['lon'])
    name = body.get('name')
    try:
        import temporal as tmp
        snaps = tmp.analyze_series(lat, lon, years=(2014, 2018, 2022, None),
                                    fetch_radius=700, char_radius=600, delay=1.0)
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({'error': f'Live historical fetch failed: {e}'}), 500

    valid = [s for s in snaps if not s.get('insufficient')]
    if not valid:
        return jsonify({'error': 'No historical OSM data found at this point.'})
    return jsonify({
        'id': -1, 'name': name or f'{lat:.4f}, {lon:.4f}', 'archetype': 'Live query',
        'lat': lat, 'lon': lon, 'snapshots': valid,
    })

@app.route('/api/morph/temporal_series')
def temporal_series():
    """Full real historical series (all curated locations) — used by the
    'History' tab. Each location carries a year-by-year character +
    genuine V2 embedding drift trajectory, computed by precompute_temporal.py
    via the exact same trained models live inference uses (see temporal.py)."""
    data = _load_temporal_series()
    if data is None:
        return jsonify({'locations': [], 'has_data': False,
                         'note': 'Run: python precompute_temporal.py'})
    locs = []
    for loc in data.values():
        snaps = [s for s in loc['snapshots'] if not s.get('insufficient')]
        locs.append({**{k: v for k, v in loc.items() if k != 'snapshots'},
                      'snapshots': [{k: v for k, v in s.items() if k != 'embedding'} for s in snaps]})
    return jsonify({'locations': locs, 'has_data': len(locs) > 0})

# Feature 4 — Cross-Country Zero-Shot Generalization removed

@app.route('/api/morph/temporal_pois', methods=['POST'])
def morph_temporal_pois():
    body = request.get_json(force=True)
    lat  = float(body['lat'])
    lon  = float(body['lon'])
    year = body.get('year')
    if str(year).lower() in ['now', 'none', '']:
        year = None
    else:
        year = int(year)

    try:
        import temporal as tmp
        import geo_snapshot as gs
        import inference as inf
        import torch
        import numpy as np
        
        records = tmp.fetch_year_records(lat, lon, year, radius=700)
        if not records:
            return jsonify({'pois': []})
        df = gs.records_to_df(records)
        res = gs.build_resources(df)
        g, sel_df = gs.local_graph(lat, lon, 600, res)
        if g is None:
            return jsonify({'pois': []})

        with torch.no_grad():
            sal = inf._saliency_model(g.x, g.edge_index).numpy()
        sal = sal.squeeze() if sal.ndim > 1 else sal
        s_min = sal.min(); s_range = (sal.max() - s_min) + 1e-8
        sal_n = (sal - s_min) / s_range
        
        pois = []
        for i, (_, row) in enumerate(sel_df.iterrows()):
            cat, val = inf.get_poi_label(row)
            pois.append({'name': str(row.get('name', '') or val), 'category': cat,
                         'value': val, 'saliency': round(float(sal_n[i]), 4),
                         'lat': float(row['lat']), 'lon': float(row['lon'])})
        pois.sort(key=lambda p: p['saliency'], reverse=True)
        return jsonify({'pois': pois})
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({'error': str(e)}), 500

# Cross-country generalization route removed

def _free_port(port):
    """Kill any existing processes listening on the given port (Windows-safe)."""
    import subprocess, sys
    try:
        result = subprocess.run(
            ['netstat', '-ano'],
            capture_output=True, text=True, timeout=5
        )
        own_pid = os.getpid()
        for line in result.stdout.splitlines():
            parts = line.split()
            if len(parts) < 5:
                continue
            addr, state, pid_str = parts[1], parts[3], parts[4]
            if f':{port}' in addr and state == 'LISTENING':
                try:
                    pid = int(pid_str)
                    if pid != own_pid:
                        subprocess.run(['taskkill', '/F', '/PID', str(pid)],
                                       capture_output=True, timeout=5)
                        print(f'[morph] Freed port {port} (killed PID {pid})')
                except Exception:
                    pass
    except Exception as e:
        print(f'[morph] Port-cleanup skipped: {e}')

if __name__ == '__main__':
    _free_port(5001)
    print('[morph] Starting GeoSemantics-Morph on http://localhost:5001')
    app.run(port=5001, debug=False, threaded=True)
